[package]
name = "plaintalkio"
version = "0.1.0"
authors = ["Johannes Hoff <johshoff@gmail.com>"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"

[dev_dependencies]
tokio-service = "0.1"

[dev_dependencies.concurrent-hashmap]
version = "0.2.1"
default-features = false
